### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xkcdjerry** [mcpython4-coding/core#4]
**Describe the bug**
The games crashes when making a new block.

**To Reproduce**
Game version:20w05a(dev)
Steps to reproduce the behavior:Make the world with barrior=false,and walk to the edge.

**Expected behavior**
The world should load a new block.

[log_01.03.20_11.15.24.txt](https://github.com/mcpython4-coding/core/files/4271284/log_01.03.20_11.15.24.txt)

**Comment by xkcdjerry** [comment]
PS:Can you make the bundle smaller?Hunderds of megabytes per day is a pain in the neck.

**Comment by uuk0** [comment]
Are you sure that you have downloaded the latest version from master-branch?

**Comment by xkcdjerry** [comment]
Sorry,I was using an outdated version……The relese branch was ok.
PS:But after an hour tring to download the master this noon,I'm about to crack.Can you please make the master smaller?
PPS:The release branch had a small bug that removing a grass block may cause the game to crash :(
The full output is here(triggered after I removed 3 grass blocks):https://paste.ubuntu.com/p/KQ733XJXMR/ (Expiration:one month)
PPPS:the code is broken,the gui package would'nt import right,you can fix this simply by adding an empty file called "__init__.py" with nothing in it to fix the ImportError and solve the bug.

**Comment by xkcdjerry** [comment]
it should be called \_\_init\_\_.py.It rendered into bold(Weird,huh?) :D

**Comment by uuk0** [comment]
Your exception is again not matching the latest version of the code (I think). The line with the exception is in the latest version "type(blockinst) != str and blockinst.NAME == "minecraft:grass_block"):" (see block/BlockDirt.py, line 35), which is not the same as in the exception.

Sorry for the big file size, I will try to make it smaller in the near future. (the biggest file is the asset file extracted from mc directly, we could implement an small function which downloads it on startup instead)

Thank you for submiting the PR, but I don't get where it fails to import the gui-package. Can you explain why we need the __init__.py file there?

**Comment by xkcdjerry** [comment]
I was using the last release branch(downloaded on March 1st)(Because 1:It was much smaller,and 2:I thought it was more stable).
So it doesn't match master,but should match relese.

OK,thanks a bunch.

If you delete the gui.__init__.py file,the import in the state folder will fail with the following error:
![图片](https://user-images.githubusercontent.com/49294431/75735462-acaead00-5d35-11ea-9313-ad80f3b03269.png)
I guess it's because there is no \_\_init\_\_.py file in the gui folder,Python doesn't know the gui is a package, so it can't be imported by the state/StatePartGame.py,if you add \_\_init\_\_.py back,everything is ok.

**Comment by xkcdjerry** [comment]
Maybe you stopped maintaing the relese branch(and/or) did not merge importent bug fixes into it?

**Comment by xkcdjerry** [comment]
PS:The right way to type \_\_int.py\_\_ without it rendering in bold is to type \\\_\\\_init\\\_\\\_.py

**Comment by uuk0** [comment]
This is stange. No other directory includes the \_\_init\_\_.py file, and it works without any exception. Can you check if the file gui/ItemStack.py exists? On my pc I got no exception at all.

PS: Can you check again if I have decreased the file size? I can do more, but I've done an change which compresses some assets.
PPS: I've been working on some bigger things which were not stable enough to merge onto release. During this process, I had fixed the grass issue. But good news, the things are going more stable now and I will be able to merge in the next days

**Comment by xkcdjerry** [comment]
Hmm.. Maybe it's a complabity error,I'm using Python 3.8.Maybe you're using a different version?
And I think if that is the case,you can add the \_\_init\_\_.py so it can work on more versions and systems.

I'm downloading it now,getting a new size soon.

OK,I'll test it again when it's merged,can you tell me when you do it?Merges to the relese branch doesn't show up.

PS:You can Swap the relase branch to main and the main branch ti rekase,that way you can delete the dev branch and refork after you merge,so there are no weird sync issuses (release is never even with master,etc.)and new users always download the stable and doesn't  have weird issues.

PPS:Maybe you can use a bugfix branch so the bug fixes are merged into release as fast as possible?It will be nice if you don't have to wait a week for bug fixed.

Thanks! :)

**Comment by xkcdjerry** [comment]
OK, the size is smaller (170MB -> 4.5MB) Thanks a bunch!

**Comment by xkcdjerry** [comment]
PPPS:Can you make a list of what types of blocks are alvible and how to "/give" them? I can't get the hang of it...Hopefully you can make a inventory 2 filled with all blocks when the player clicks "e" in gamemode 1.(Like in MC)
PPPPS:Maybe you can shift the code around a bit so that the new chunk spawns when the player is 10 blocks away from the edge?This will make it seem more naturle and (I think) woulden't need much code.

**Comment by xkcdjerry** [comment]
Dude, you forgot to add the resourcepacks/minecraft.zip :(

**Comment by uuk0** [comment]
I'm also using python 3.8, 

For an complete list of blocks use the "/registryinfo block"-command which will print out all blocks with their name (the command exists also for items).

I'm working on the creative inventory. I'm currently having trouble with rendering the page selection buttons

The problem with the generation of new chunks in-game is at the moment that it is connected to the collision sytem which will see if you border an ungenerated chunk. This will need some work, but the idea is good, I will try to implement it soon.

Sorry, I forgot to push the fix for the missing asset file yesterday. Should be fixed now

PS: I am fixing at the moment the last issues in the master-branch, after that I will merge it onto release and change the main-branch to release.

**Comment by uuk0** [comment]
PPS: I've found some stuff which will result in an much smaller size (~100MB) by removing the sound files (which are unused at the moment). When the program will need them, we can include it again, but until than, it will help with the file size

**Comment by xkcdjerry** [comment]
That's weird,I don't know what's the matter,does yours crash when you add an \_\_init\_\_ file?

Maybe you can use a no-select big inventory+a scrollbar,without the type selecters,that would probley be easer.

OK,thanks.

I'm downloading it now.

OK,thanks.

So you mean the ->4.5MB file size is just because you forgot to add the zip file,and if you add the zip file and remove the sound,the zip file's size will be around 100MB.Right?

**Comment by uuk0** [comment]
The file size change from before when I had included the sound files to now is ~100MB,

I will merge your pull request, I do not have this problem, but as long as it occures on your machine, it is worth including it.

**Comment by xkcdjerry** [comment]
So it's about 70MB.
PS:The give command seems to crash the game when it type it wrong :(
Maybe it can be fixed by adding a error check and showing it in the GUI (and/or) log a message?

**Comment by uuk0** [comment]
Can you give me some more information about the crash? I did not manage to reproduce the crash with the release-branch

Theoretically, the exception should be handled in CommandParser.py, line 67-80 which make sure that a) an error occuring during decoding the values is handled and b) an error during executing the action is handled. If this system fails for you, I need the exception from it.

**Comment by xkcdjerry** [comment]
Weird, this did not pop up again,so problem solved :)
But I found another error:
Sprung when I use all those nice default arguments,and then I removed a few blocks, and ka-boom:
![图片](https://user-images.githubusercontent.com/49294431/76087849-ef041280-5ff1-11ea-9e30-610ddb714b5c.png)
I guess it's the same bug as before,I did a bug fix,will pull soon. :)

**Comment by xkcdjerry** [comment]
PS: Can you speed up the load?You made it to ~7secs before,now it's ~25secs :(

**Comment by uuk0** [comment]
Sorry for the exception, this was an merge-error. I will fix it in an few minutes.

Can you analyse the loading time a little bit further? What phase is taking long? Or is everything slow?
(in the lowest bar in loading, you see in which loading phase the game is currently in)

**Comment by xkcdjerry** [comment]
Sorry,I typed it wrong,I ment the world gen,not the load. :(

**Comment by uuk0** [comment]
Ok, world gen is a little bit complicated to analyse. In your log, there is printed out an line "generating layer <layername>". Which layer is taking the most time, or is it all layers?

**Comment by xkcdjerry** [comment]
Let me see...

**Comment by xkcdjerry** [comment]
It seems that each layer doesn't take long, but there are symply so much of them

**Comment by uuk0** [comment]
Ok, the layer count is needed as it is. Can you try the following: go to Block/Block.py an delete the line in __init__ where uuid is set
This could affect the generation time

**Comment by xkcdjerry** [comment]
Maybe you can gen fewer blocks?Added with the distance-load method,It can make for A LOT less time :)

**Comment by uuk0** [comment]
I will add an option to select height-map-range.
When it's less height, it's less block that are added

**Comment by uuk0** [comment]
Ok, found the point for the height-range-selection. Go to world/gen/biome/BiomePlains.py, line 26 and decrease both values (it's an range for the height selected by the height-map-generator)

**Comment by xkcdjerry** [comment]
I halved both values,see what will happen

**Comment by xkcdjerry** [comment]
Not much good,still 25secs :(

**Comment by uuk0** [comment]
Hmm, this should decrease generation time by a lot (~also by half) if it's the adding of the blocks. 
I'm working now on an system which will generate all chunks around the chunk the player is in, but it's not working at the moment. 
It may be that it's cause by some rendering system slowdown (which is independend from the world height because only the top blocks are shown). I will try to optimize the system in the near future, but it will be complicated due to the complex system behind it.

**Comment by xkcdjerry** [comment]
Maybe you can first debug it to see if it got the right chunks,if the chunks are correct,then it's the render's falt :)

**Comment by uuk0** [comment]
Can you try the dev-branch now? I have tried to improve it a little bit, and it may have worked

**Comment by xkcdjerry** [comment]
Sorry,gotta sleep,it's about 11 p.m. here,bye.

**Comment by uuk0** [comment]
bye
